version: '3.8'
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongodb:27017/mydb

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileDev
      args:
        REACT_APP_BASE_URL: http://localhost:8000
        NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3001:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8000

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
