version: '3.8'
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=pdftoolbox_dev_db
      - API_PREFIX=/
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=sine_pugna_nulla_vicrtoria
      - GEOIP_API_URL=https://ipapi.co

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_BASE_URL: http://localhost:8000
        NODE_ENV: development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 3001:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BASE_URL=http://localhost:8000

  mongodb:
    image: mongo:latest
    container_name: mongo_local
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=pdftoolbox_dev_db
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
    name: dev_mongo_data
  frontend_node_modules:
    name: frontend_node_modules