version: '3.8'
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongodb:27017/mydb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:5173
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
