version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_server
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydb
      PYTHONUNBUFFERED: '1'
      FASTAPI_ROOT_PATH: /PDFToolbox/api

    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_server
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 3001:80

volumes:
  mongo_data:
